### ISSUE TITLE
reading into different ways of estimating information

### ISSUE THREAD

**Issue by lukeeffenberger** [neuroinfo-os/deep-bottleneck#11]

**Comment by jrebstadt** [comment]
Add to glossary information about different approaches and where they are used.

**Comment by lukeeffenberger** [comment]
i already wrote something about binning.
the other two would be then the kraskov estimator (https://arxiv.org/abs/cond-mat/0305641) and the kolchinsky paper (http://www.mdpi.com/1099-4300/19/7/361), but only the ones that are used in the iclr2018 implementation

I guess would be best if we split up. Preferences?
