### ISSUE TITLE
Can we save and view plots directly in mongodb and sacredboard?

### ISSUE THREAD

**Issue by JarnoRFB** [neuroinfo-os/deep-bottleneck#17]

**Comment by junbohuang** [comment]
Every experiment is sacred
Every experiment is great
If an experiment is wasted
God gets quite irate

**Comment by JarnoRFB** [comment]
Maybe files can be added via artifacts. Viewing in sacredboard seems not to be possible, but issue is tracked here https://github.com/chovanecm/sacredboard/issues/81. Please upvote!

**Comment by JarnoRFB** [comment]
Plots are saved now as binary data.
