### ISSUE TITLE
Ask team tishby regarding unexplained phenomena in relu plots

### ISSUE THREAD

**Issue by felixmzd** [neuroinfo-os/deep-bottleneck#20]

**Comment by lukeeffenberger** [comment]
we probably could just write a comment on youtube (he is very active under the videos of his talks) to get a start in the right direction

**Comment by felixmzd** [comment]
https://planspace.org/20180213-failure_to_replicate_schwartz-ziv_and_tishby/ also raises some very similar questions as ours to team Tishby.
