### ISSUE TITLE
Spike: Think about binning

### ISSUE THREAD

**Issue by JarnoRFB** [neuroinfo-os/deep-bottleneck#25]
Can we improve binning by looking at the mutual information between the activation and y_hat.

**Comment by lukeeffenberger** [comment]
dammit again :D

**Comment by lukeeffenberger** [comment]
- activations are binned to obtain discrete representations
- a necessary condition for these representations to be valid is: activations that are discretized to same representation should produce the same output y_hat, i.e. H(y_hat|T_k) = 0
- by plotting H(y-hat|T_k) against the epochs for each layer we could maybe supervise how valid the binning is that we are doing
- hopefully one could see, that the bins are tanh are "valid", while the bins for relu loose their "validity"
- from this one we maybe could design some algorithm that ensures that we bin in a "valid" way
