### ISSUE TITLE
Investigate if ReLU maybe just does not solve the problem as well as tanh

### ISSUE THREAD

**Issue by lukeeffenberger** [neuroinfo-os/deep-bottleneck#31]
I included the validation data and ran the script once with relu once with tanh.

relu after 10000 epochs loss: 0.018 - acc: 0.9942 - val_loss: 0.3670 - val_acc: 0.9438
already reached this after roughly 240 epochs.

tanh after 10000 epochs loss: 0.0048 - acc: 0.9994 - val_loss: 0.1795 - val_acc: 0.9744
tanh was constantly slowly improving even after 10000 epochs.

**Comment by felixmzd** [comment]
Good point, to be more sure about the performance we should also do ~10-20 runs each.
