### ISSUE TITLE
tanh does not show compression if experiment is stopped at 94% test error

### ISSUE THREAD

**Issue by lukeeffenberger** [neuroinfo-os/deep-bottleneck#38]

**Comment by jrebstadt** [comment]
Implemented early stopping for 94 % validation accuracy.
First using binning:
![infoplane_tanh_10-7-5-4-3_bin_first](https://user-images.githubusercontent.com/11737615/40429610-62e5b5b6-5ea3-11e8-9dbf-11655a9c69b7.png)
Using lower:
![infoplane_tanh_10-7-5-4-3_lower](https://user-images.githubusercontent.com/11737615/40429677-8abddf78-5ea3-11e8-8a8d-ebf588a9b5eb.png)

**Comment by felixmzd** [comment]
We should write this down in a notebook

**Comment by felixmzd** [comment]
try relu once again with initial bias.

**Comment by felixmzd** [comment]
relu goes beyond 94 % when experiment is done with zero-mean harmonics dataset, still not showing any compression.
