### ISSUE TITLE
Think about an objective metric for compression

### ISSUE THREAD

**Issue by JarnoRFB** [neuroinfo-os/deep-bottleneck#40]

**Comment by lukeeffenberger** [comment]
the standard metric for lossy compression is measuring rate-distortion, but that actually measures  how much errors we make when compressing. and we actually want to make errors, right?

**Comment by lukeeffenberger** [comment]
if we are just talking about if the network is in the end compressing, rüdiger is probably right. it is enough to look at how compressed the representations are in the end with respect to the information that they still have about the output

**Comment by lukeeffenberger** [comment]
maybe one could run a glm on the all the information measures to get the validation accuracy to see if theres is a connection?:D

**Comment by lukeeffenberger** [comment]
it might be enough to look at H(T) in contrast to H(X) to see how compressed a representation is. maybe its even enough to look at the last layer. does it matter in which layers the network compresses?

**Comment by JarnoRFB** [comment]
> the standard metric for lossy compression is measuring rate-distortion, but that actually measures how much errors we make when compressing. and we actually want to make errors, right?

Why do we want to make errors? Not with respect to the label or am I missing something :D

**Comment by lukeeffenberger** [comment]
we want to lose information. as far as I undestood the rate-distortion measures the ratio of how much you compress to how much information you lose. maybe we want this? i dont know. lets discuss tomorrow:)

**Comment by felixmzd** [comment]
Possible way to do this is to fit a polynomial (i.e 2nd or 3rd order) along the points in the information plane for a specific layer. The parameters of the polynomial quantify "compression"
