### ISSUE TITLE
Use bigger networks for ReLU to get better (>94%) and show compression? 

### ISSUE THREAD

**Issue by lukeeffenberger** [neuroinfo-os/deep-bottleneck#55]

**Comment by lukeeffenberger** [comment]
![relu with bigger network](https://user-images.githubusercontent.com/27016677/40831205-b360a708-6588-11e8-9b7a-9c3401f8b957.png)

**Comment by lukeeffenberger** [comment]
I can't say which architecturee this was, something like 16-12-10-6-4. Note that the plot is only for 4000 epochs.

**Comment by felixmzd** [comment]
unsolved and postponed
