### ISSUE TITLE
Understand the dependency between the MI and the specific dataset (12 vs 14 as limits for x-axis in harmonics and MNIST)

### ISSUE THREAD

**Issue by jrebstadt** [neuroinfo-os/deep-bottleneck#62]

**Comment by lukeeffenberger** [comment]
as we already discussed yesterday:
I(X;T) = H(X) - H(X|T) and same for Y
--> axes are bounded by H(X) / H(Y)  
--> log2(2^12) = 12
log2(256^784) ~= 17

**Comment by lukeeffenberger** [comment]
but this is actually only the most upper bound. for ibnet it makes sense, for mnist it also makes sense that it is actually lower (14) because our data is not spread full in the possible space of images
