### ISSUE TITLE
Try linear regression and perceptron as baseline

### ISSUE THREAD

**Issue by JarnoRFB** [neuroinfo-os/deep-bottleneck#69]
Is the harmonics problem really so complicated? Let's try linear regression as a baseline.

**Comment by lukeeffenberger** [comment]
![image](https://user-images.githubusercontent.com/27016677/41612543-8730dddc-73f3-11e8-9ab1-09727b72436b.png)
no hidden layer, more or less a perceptron. stops learning at 0.8718, still "compression" is visible

**Comment by felixmzd** [comment]
unsolved and postponed
