### ISSUE TITLE
Find a way to quantify lossy compression

### ISSUE THREAD

**Issue by JarnoRFB** [neuroinfo-os/deep-bottleneck#70]
Can one factor in the accuracy and the compression ratio.

**Comment by felixmzd** [comment]
Possible way to do this is to fit a polynomial (i.e 2nd or 3rd order) along the points in the information plane for a specific layer. The parameters of the polynomial quantify "compression"

**Comment by felixmzd** [comment]
I think this is a duplicate of #40
